spring.application.name=PodzialObowiazkow
spring.datasource.url=jdbc:postgresql://localhost:5332/postgres
spring.datasource.username=majkel
spring.datasource.password=password


spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

logging.level.liquibase=INFO